name: Build and Publish to TestPyPI

on:
  workflow_dispatch: {}
  push:
    tags:
      - 'v*' # Ще се задейства при създаване на таг, например v0.1.0

jobs:
  build-n-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write  # Задължително за Trusted Publishing

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install build tools
      run: python -m pip install build

    - name: Build wheel and sdist
      run: python -m build

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: test.pypi.org
